### PR TITLE
parity: Release version 0.7.0

### PR DESCRIPTION
**Pull request by croaky**
* Release notes: https://github.com/croaky/parity/releases/tag/v0.7.0
* Using sha256 per `brew create` instructions in:
  https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#grab-the-url
* Update README for Parity and Pick.

### CODE REVIEW

**Comment by croaky** [comment]
Ready for review @thoughtbot/parity

**Comment by geoffharcourt** [comment]
@croaky, I might be doing something wrong, but when I run `shasum -a 256 parity-0.7.0-osx.tar.gz`, I get a different hash:

```shell
[ /tmp ] shasum -a 256 parity-0.7.0-osx.tar.gz                                                                                                        [2.2.2]
1a6fc22fbce087cc5bc047bfe6ad22cf901b78d322d2fc3823ee2a62457b88b8  parity-0.7.0-osx.tar.gz
```

**Comment by mjankowski** [comment]
I downloaded from github and see the same thing Dan included...

```
lemonzest:Desktop mjankowski$ shasum -a 256 parity-0.7.0-osx.tar.gz 
3c9b9bf2a950c7a18e67800bdd6676cb415dd17a3acb4189a85184804d403f33  parity-0.7.0-osx.tar.gz

**Comment by gabebw** [comment]
When I run `brew create`, I see Dan and Matt's checksum. But when I hash it locally, I get a third unique checksum, different from that one and different from Geoff's:

```
$ curl -O https://github.com/thoughtbot/parity/releases/download/v0.7.0/parity-0.7.0-osx.tar.gz  
$ shasum -a 256 parity-0.7.0-osx.tar.gz                                                                                                                                                                                                                                           a9c67ff0c9982600efb2fd0f31aa76231d0b402eb3c8cf2010f295f97f26004c  parity-0.7.0-osx.tar.gz
```

I'm inclined to go with the hash that `brew create` and Matt found.

Interesting post-script: `Digest::SHA2` gives the same answer as `shasum -a 256` at the command line, so I don't know what Homebrew is doing:

```
irb> Digest::SHA2.hexdigest(File.read("/Users/gabe/parity-0.7.0-osx.tar.gz")) 
=> "a9c67ff0c9982600efb2fd0f31aa76231d0b402eb3c8cf2010f295f97f26004c"
```

**Comment by geoffharcourt** [comment]
I get an error when I run `brew create` that's unrelated. If you get a match when you run that command, I think this is just a false alarm on my part.

**Comment by gabebw** [comment]
The important thing is, when I copy the proposed changes in this PR into my local formula, `brew install parity` works.

**Comment by gabebw** [comment]
Therefore: :+1:

**Comment by croaky** [comment]
Yup, I went with `brew create` to generate it.

**Pull request merged**
