### PR TITLE
Update Parity formula for v0.9.2

### PR DESCRIPTION
**Pull request by geoffharcourt**
* Faster deploys, less interaction with development-machine Rake

### CODE REVIEW

**Comment by gylaz** [comment]
:+1:

**Comment by axelson** [comment]
@geoffharcourt You forgot to update the `parity-0.9.1-osx.tar.gz` portion of the file.

**Comment by geoffharcourt** [comment]
@axelson thank you for reporting that. I've pushed a new 0.9.2 formula, and then a 0.9.2.1 formula in case existing users don't get updated by that update. Please let me know here if you have further problems.

**Comment by axelson** [comment]
@geoffharcourt works great! Thanks.

**Pull request merged**
