### PR TITLE
rcm: install manpages

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by geoffharcourt** [comment]
cc: @georgebrock @mike-burns

**Comment by mike-burns** [comment]
The `install` target doesn't call `install-man`?

The `install-man` target produces the desired results?

**Comment by mike-burns** [comment]
The OpenBSD port just does a `make install` (hard to see from this: http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/sysutils/rcm/Makefile?rev=1.2&content-type=text/x-cvsweb-markup) and it certainly installs the man pages (can be seen here: http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/sysutils/rcm/pkg/PLIST?rev=1.1&content-type=text/x-cvsweb-markup). So what's going on in Homebrew? Are they being installed into the wrong path?

**Comment by georgebrock** [comment]
On my OS X system, I installed via homebrew and got the man pages:

```
$ whatis rcm
lsrc(1)                  - show dotfiles files managed by rcm
mkrc(1)                  - bless files into a dotfile managed by rcm
rcdn(1)                  - remove dotfiles as managed by rcm
rcm(7)                   - dotfile management
rcrc(5)                  - configuration for rcm
rcup(1)                  - update and install dotfiles managed by rcm
```

They're installed in `/usr/local/Cellar/rcm/1.3.0/share/man/`, and symlinked in `/usr/local/share/man`, which is normal for a program installed with homebrew.

**Comment by mike-burns** [comment]
Closing this. Let us know whether there's something we're missing, @robsonpeixoto .

**Pull request closed without merging**
